gpu_variant:
  - None
  - cuda-12                    # [(linux and x86_64)]

cuda_compiler_version:
  - None                       
  - 12.8                       # [(linux and x86_64)]

zip_keys:                      # [(linux and x86_64)]
  -                            # [(linux and x86_64)]
    - gpu_variant              # [(linux and x86_64)]
    - cuda_compiler_version    # [(linux and x86_64)]

skip_cuda_pbp:
  - true

OSX_SDK_VER:  # [osx]
  - 12.3      # [osx]

c_compiler:
  - clang
cxx_compiler:
  - clangxx  # [unix]
  - clang    # [win]

c_compiler_version:
  - 20
cxx_compiler_version:
  - 20
