gpu_variant:
  - None
  - cuda-12                    # [(linux and x86_64)]

cuda_compiler_version:
  - None                       
  - 12.4                       # [(linux and x86_64)]

cudnn:                         # [(linux and x86_64)]
  - '9.1.1.17'                 # [(linux and x86_64)]
nccl:                          # [(linux and x86_64)]
  - '2.21.5.1'                 # [(linux and x86_64)]
cuda_compiler:                 # [(linux and x86_64)]
  - cuda-nvcc                  # [(linux and x86_64)]

zip_keys:                      # [(linux and x86_64)]
  -                            # [(linux and x86_64)]
    - gpu_variant              # [(linux and x86_64)]
    - cuda_compiler_version    # [(linux and x86_64)]

skip_cuda_pbp:
  - true

OSX_SDK_VER:               # [osx]
  - 12.3                   # [osx]

c_compiler:                # [win]
  - clang                  # [win]
cxx_compiler:              # [win]
  - clang                  # [win]

c_compiler_version:        # [win]
  - 17.0.6                 # [win]
cxx_compiler_version:      # [win]
  - 17.0.6                 # [win]