gpu_variant:
  - None
  - cuda-12                    # [(linux and x86_64)]

cuda_compiler_version:
  - None                       
  - 12.8                       # [(linux and x86_64)]

zip_keys:                      # [(linux and x86_64)]
  -                            # [(linux and x86_64)]
    - gpu_variant              # [(linux and x86_64)]
    - cuda_compiler_version    # [(linux and x86_64)]

skip_cuda_pbp:
  - true

OSX_SDK_VER:               # [osx]
  - 12.3                   # [osx]

c_compiler:                # [win]
  - clang                  # [win]
cxx_compiler:              # [win]
  - clang                  # [win]

c_compiler_version:        # [win]
  - 20                     # [win]
cxx_compiler_version:      # [win]
  - 20                     # [win]
